/*****************************************************************************
 * File generated by HDevelop Version 23.11
 *
 * Do not modify!
 *****************************************************************************/

#ifndef HDEV_PHOTO_ANALYSES_APP_H
#define HDEV_PHOTO_ANALYSES_APP_H

#ifndef __APPLE__
  #include <halconcpp/HalconCpp.h>
#else
  #include <HALCONCpp/HalconCpp.h>
#endif

namespace hdev_photo_analyses_app {

/*****************************************************************************
 * SetResourcePath
 *****************************************************************************
 * Use SetResourcePath in your application to specify the location of the 
 * HDevelop script or procedure library.
 *****************************************************************************/
  void SetResourcePath(const char* resource_path);
#ifdef _WIN32
  void SetResourcePath(const wchar_t* resource_path);
#endif

  void find_digits(
    HalconCpp::HObject const& Image,
    HalconCpp::HTuple* Area,
    HalconCpp::HTuple* Confidence);


    
};

#endif